name: Deploy to AWS Elastic Beanstalk
run-name: Deploy application to AWS Elastic Beanstalk on ${{ github.ref }}
on:
  push:
    branches: [main]
jobs:
  Deploy-AWS-EB:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Generate deployment package
        run: zip -r deploy.zip . -x "*.git*" "compose.yml" "tests/*" "Dockerfile.dev"
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: my-website-app
          environment_name: my-website-env
          existing_bucket_name: ${{ secrets.AWS_S3_BUCKET }}
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: deploy.zip
